"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000
palette = "mfd-mono"

format = """
${env_var.NIX_FLAKE_INSIDE}\
${env_var.NIX_FLAKE_OUTSIDE}\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$cmd_duration\
$line_break\
$character"""

[hostname]
ssh_only = true
format = "[@$hostname]($style) "
style = "mfd_bright"

[directory]
style = "mfd_bright"
read_only_style = "bold mfd_red"

[character]
success_symbol = "[❯](bold mfd_green)"
error_symbol = "[❯](bold mfd_red)"
vimcmd_symbol = "[❮](bold mfd_green)"
vimcmd_replace_one_symbol = "[❮](bold mfd_green)"
vimcmd_replace_symbol = "[❮](bold mfd_green)"
vimcmd_visual_symbol = "[❮](bold mfd_green)"

[git_branch]
format = "[on](mfd_bright) [$symbol$branch]($style) "
symbol = " "
style = "bold mfd_bright"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "bold mfd_red"
conflicted = "="
untracked = "?"
modified = "!"
staged = "+"
renamed = "»"
deleted = "✘"
stashed = '\$'
ahead = "⇡"
behind = "⇣"
diverged = "⇕"
up_to_date = ""

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "mfd_bright"

[cmd_duration]
format = "[$duration]($style) "
style = "mfd_bright"

[env_var.NIX_FLAKE_INSIDE]
format = "[λ]($style) "
style = "bold mfd_green"

[env_var.NIX_FLAKE_OUTSIDE]
format = "[λ]($style) "
style = "bold mfd_red"

[lua]
disabled = true

[python]
disabled = true

[palettes.mfd-mono]
mfd_bg = "#0A0B0A"
mfd_bright = "#F4F4FF"
mfd_red = "#F36C7A"
mfd_green = "#7DCE8C"
