typeset -U path PATH fpath

# Paths: prefer Nix tools while keeping Homebrew available as a fallback.
path=(
  "$HOME/.nix-profile/bin"
  "/nix/var/nix/profiles/default/bin"
  "$HOME/.local/bin"
  "/opt/homebrew/bin"
  "/opt/homebrew/sbin"
  "$HOME/.lmstudio/bin"
  "/usr/bin"
  "/bin"
  "/usr/sbin"
  "/sbin"
)

# Integrations
(( $+commands[zoxide] )) && eval "$(zoxide init zsh)"
(( $+commands[mise] )) && eval "$(mise activate zsh)"
(( $+commands[starship] )) && eval "$(starship init zsh)"

if (( $+commands[fzf] )); then
  (( $+commands[bat] )) && export FZF_CTRL_T_OPTS="--preview 'bat --style=numbers --color=always {}'"
  source <(fzf --zsh)
  bindkey -r '^[c'
fi

# Editor, aliases, and keybindings
export EDITOR="nvim"
export VISUAL="$EDITOR"

alias ls='eza --group-directories-first'
alias box='ssh phongndo@dp'
alias dot='git -C "$HOME/nix-config"'
alias hm='home-manager switch --flake "$HOME/nix-config#dp"'

autoload -Uz edit-command-line
zle -N edit-command-line
bindkey '^G' edit-command-line

ulimit -n 65536
