[settings]
minimum_release_age = "0s"

[tools]
bun = "latest"
codex = "latest"
deno = "latest"
node = "latest"
python = "latest"
copilot-cli = "latest"
grok = "latest"
uv = "latest"
opencode = "latest"
pi = "latest"
