[settings]
minimum_release_age = "0s"

[settings.npm]
package_manager = "npm"

[plugins]
co = "https://github.com/anysphere/origin-cli-asdf"

[tools]
bun = "latest"
codex = "latest"
deno = "latest"
python = "latest"
copilot-cli = "latest"
uv = "latest"
opencode = "latest"
pi = "latest"
node = "latest"
"npm:@deepseek-ai/dsh" = "latest"
co = "latest"
fx = "latest"
cursor-agent = "latest"
