(
 (readline-input-history
  (
   #"(exit)"
   #"x"
   #"(if (= x 0) 0 (/ 1 x))"
   #"(or (boolean=? sunny #false) (boolean=? friday #true))"
   #"(or (= sunny #false) (= friday #true))"
   #"(or (== sunny #false) (== friday #true))"
   #"(define friday #false)"
   #"(define sunny #true)"
   #"(define cat /var/folders/07/j9b7qv3x4j58z0nhnz59316m0000gn/T/TemporaryItems/NSIRD_screencaptureui_pV4SZZ/Screenshot\\ 2026-04-08\\ at\\ 14.25.40.png)"
   #"(+ (image-width (circle 10 \"solid\" \"red\"))\n   (image-height (rectangle 10 20 \"solid\" \"blue\")))"
   #"(rectangle 10 20 \"solid\" \"blue\")"
   #"(rectanle 10 20 \"solid\" \"blue\")"
   #"(circle 20 \"solid\" \"red\")"
   #"(require 2htdp/image)"
   #"(require 2hdtp/image)"
   #"(string-append (substring str 0 i) \"_\" (substring str i (string-length str)))"
   #"(substring str 0 4)"
   #"(substring str 1 4)"
   #"str"
   #"(string-ith i \"chatccahtchat\")"
   #"(string-ith i (string-append \"_\" str))"
   #"(define i 5)"
   #"(define str \"helloworld\")"
   #"(+ (string-length  42) 1)"
   #"(+ (string-length (number->string 42)) 2)"
   #"2->string"
   #"(string-ith \"wordle\" 2)"
   #"(string-length prefix)"
   #"(string-append prefix \"_\" suffix)"
   #"(define suffix \"world\")"
   #"(define prefix \"hello\")"
   #"(string-append \"what a \" \"lovely\" \"day\" \" 4 Racket\")"
   #"(dist 3 4)"
   #"(define (dist x y)\n  (sqrt( +\n         (* x x)\n         (* y y)\n         )\n       )\n  )"
   #"(define (dist x y) (sqrt( + ( * x x ) ( * y y )))\n  )"
   #"(define (dist x y) (\n                    sqrt ( + ( * x x ) ( * y y )))\n  )"
   #"(* x y)"
   #"(+ x 10)"
   #"y"
   #"x"
   #"(sqrt (+ (* x x) (* y y)))"
   #"(define y 4)"
   #"(define x 3)"
   #"(sqrt 2)"
   #"(/ 4 6)"
   #"(/ 4 4)"
   #"(/ 4.5 3)"
   #"(sin 0)"
   #"(add1 2)"
   #"(+ 1 (+ 3 4 ) ( + 3 4))"
   #"(exit)"
   #"(+ 1 2 3)"
   #"(+ 1 2)"
   #"(exit)"
   #"(clear)"
   #"clear"
   #"(abs-val 49)"
   #"(abs-val -49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (- x)\n    x))"
   #"(abs-val 49)"
   #"(abs-val -49)"
   #"j(define (abs-val x)\n  (if (negative? x)\n    (- x)\n    x))"
   #"(abs-val 49)"
   #"(abs-val -49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (* -1 x)\n    x))"
   #"(exit)"
   #"main.rkt"
   #"(abs-val 49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (* -1 x)\n    (x)\n    )\n  )"
   #"(exit\n )"
   #"(abs-bal 49)"
   #"(abs-bal 49\n         )"
   #"(abs-val -49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (* -1 x)\n    x\n    )\n  )"
   #"(exit)"
   #"(add 3 5)"
   #"(define (add x y)\n  (+ x y))"
   #"p"
   #"(exit)"
   #"(add 3 5)"
   #",enter \"main.rkt\""
   #"(add 3 5)"
   #",enter \"main.rkt\""
   #"x"
   #",enter \"main.rkt\""
   #"x"
   #",enter \"main.rkt\""
   #"x"
   #",enter \"main.rkt\""
   #",enter main.rkt"
   #"(exit)"
   #",enter (file \"main.rkt\")"
   #",enter main.rkt"
   #"(exit)"
   #"enter main.rkt"
   #",enter main.rkt"
   #"(exit)"
   #"(q)"
   #"bt"
   #"(exit)"
   #"(quit)"
   #"q()"
   #"(exit)"
   #"quit"
   #"exit"
   #"(+ 3 8)"
  ))
)
