(
 (readline-input-history
  (
   #"(exit)"
   #"(clear)"
   #"clear"
   #"(abs-val 49)"
   #"(abs-val -49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (- x)\n    x))"
   #"(abs-val 49)"
   #"(abs-val -49)"
   #"j(define (abs-val x)\n  (if (negative? x)\n    (- x)\n    x))"
   #"(abs-val 49)"
   #"(abs-val -49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (* -1 x)\n    x))"
   #"(exit)"
   #"main.rkt"
   #"(abs-val 49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (* -1 x)\n    (x)\n    )\n  )"
   #"(exit\n )"
   #"(abs-bal 49)"
   #"(abs-bal 49\n         )"
   #"(abs-val -49)"
   #"(define (abs-val x)\n  (if (negative? x)\n    (* -1 x)\n    x\n    )\n  )"
   #"(exit)"
   #"(add 3 5)"
   #"(define (add x y)\n  (+ x y))"
   #"p"
   #"(exit)"
   #"(add 3 5)"
   #",enter \"main.rkt\""
   #"(add 3 5)"
   #",enter \"main.rkt\""
   #"x"
   #",enter \"main.rkt\""
   #"x"
   #",enter \"main.rkt\""
   #"x"
   #",enter \"main.rkt\""
   #",enter main.rkt"
   #"(exit)"
   #",enter (file \"main.rkt\")"
   #",enter main.rkt"
   #"(exit)"
   #"enter main.rkt"
   #",enter main.rkt"
   #"(exit)"
   #"(q)"
   #"bt"
   #"(exit)"
   #"(quit)"
   #"q()"
   #"(exit)"
   #"quit"
   #"exit"
   #"(+ 3 8)"
  ))
)
