layout = "dynamic"
line_wrapping = false
live_reload = true
syntax_highlighting = true
theme = "mfd-mono"

[diff]
context_expand = 20

[notifications]
mode = "default"

[ui.toast]
corner = "top-right"
verbosity = "verbose"
