if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Darwin")
  message(FATAL_ERROR "homebrew-llvm-macos.cmake is only intended for macOS hosts")
endif()

include_guard(GLOBAL)

execute_process(
  COMMAND brew --prefix llvm
  OUTPUT_VARIABLE HOMEBREW_LLVM_PREFIX
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET
)

if(NOT HOMEBREW_LLVM_PREFIX OR NOT EXISTS "${HOMEBREW_LLVM_PREFIX}/bin/clang++")
  message(FATAL_ERROR "Homebrew llvm is not installed. Run: brew install llvm")
endif()

execute_process(
  COMMAND brew --prefix ninja
  OUTPUT_VARIABLE HOMEBREW_NINJA_PREFIX
  OUTPUT_STRIP_TRAILING_WHITESPACE
  ERROR_QUIET
)

execute_process(
  COMMAND xcrun --sdk macosx --show-sdk-path
  OUTPUT_VARIABLE MACOS_SDK_PATH
  OUTPUT_STRIP_TRAILING_WHITESPACE
  RESULT_VARIABLE MACOS_SDK_RESULT
)

if(NOT MACOS_SDK_RESULT EQUAL 0 OR NOT EXISTS "${MACOS_SDK_PATH}")
  message(FATAL_ERROR "Could not find the macOS SDK via xcrun")
endif()

set(CMAKE_C_COMPILER "${HOMEBREW_LLVM_PREFIX}/bin/clang" CACHE FILEPATH "Homebrew clang" FORCE)
set(CMAKE_CXX_COMPILER "${HOMEBREW_LLVM_PREFIX}/bin/clang++" CACHE FILEPATH "Homebrew clang++" FORCE)
set(CMAKE_AR "${HOMEBREW_LLVM_PREFIX}/bin/llvm-ar" CACHE FILEPATH "Homebrew llvm-ar" FORCE)
set(CMAKE_RANLIB "${HOMEBREW_LLVM_PREFIX}/bin/llvm-ranlib" CACHE FILEPATH "Homebrew llvm-ranlib" FORCE)
set(CMAKE_OSX_SYSROOT "${MACOS_SDK_PATH}" CACHE PATH "macOS SDK" FORCE)

if(HOMEBREW_NINJA_PREFIX AND EXISTS "${HOMEBREW_NINJA_PREFIX}/bin/ninja")
  set(CMAKE_MAKE_PROGRAM "${HOMEBREW_NINJA_PREFIX}/bin/ninja" CACHE FILEPATH "Homebrew ninja" FORCE)
endif()

set(FIBER_USE_HOMEBREW_LIBCXX ON CACHE BOOL "Use Homebrew LLVM libc++/libunwind")

if(FIBER_USE_HOMEBREW_LIBCXX)
  add_compile_definitions(_LIBCPP_DISABLE_AVAILABILITY)

  set(_HOMEBREW_LLVM_LINK_FLAGS
    "-L${HOMEBREW_LLVM_PREFIX}/lib/c++ -Wl,-rpath,${HOMEBREW_LLVM_PREFIX}/lib/c++ -L${HOMEBREW_LLVM_PREFIX}/lib/unwind -Wl,-rpath,${HOMEBREW_LLVM_PREFIX}/lib/unwind"
  )

  set(CMAKE_EXE_LINKER_FLAGS_INIT "${_HOMEBREW_LLVM_LINK_FLAGS} ${CMAKE_EXE_LINKER_FLAGS_INIT}")
  set(CMAKE_SHARED_LINKER_FLAGS_INIT "${_HOMEBREW_LLVM_LINK_FLAGS} ${CMAKE_SHARED_LINKER_FLAGS_INIT}")
  set(CMAKE_MODULE_LINKER_FLAGS_INIT "${_HOMEBREW_LLVM_LINK_FLAGS} ${CMAKE_MODULE_LINKER_FLAGS_INIT}")
  set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "-lunwind ${CMAKE_CXX_STANDARD_LIBRARIES_INIT}")
endif()
